<?php

/**
 * @file
 * Primary module hooks for foia_annual_data_report module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\node\NodeInterface;
use Drupal\Core\Url;
use Drupal\Core\Ajax\RedirectCommand;

/**
 * Implements hook_form_form_alter().
 */
function foia_annual_data_report_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Look for this string to match an Annual Data Report (ADR).
  $adr_string = 'node_annual_foia_report_data_';

  // Look for the adr string in the form id.
  if (substr($form_id, 0, strlen($adr_string)) === $adr_string) {

    // Use the Service to get info for an annual data report form.
    $adr_form_info = \Drupal::service('annual_data_report.form_displays')->info($form_id);

    // This is an Annual Data Report form.
    if ($adr_form_info['is_adr_form']) {

      // Add in the previous and next links if there are any.
      if (!empty($adr_form_info['form_nav'])) {
        $form['form_section'] = [
          '#type' => 'value',
          '#value' => $adr_form_info['form_section'],
        ];
        $form['form_section_links'] = [
          '#markup' => $adr_form_info['form_nav'],
        ];
      }

      // Add the AJAX save callbacks.
      foia_annual_data_report_ajax_existing_node($form);
      foia_annual_data_report_set_default_report_year($form);

      // Attach the css to transform the secondary local links to a dropdown.
      $form['#attached']['library'][] = 'foia_annual_data_report/foia_annual_data_report_form_display_links';

      // Don't try to alter redirect on default form display.
      if ($adr_form_info['form_section'] != 'edit') {
        // Add a submit handler to redirect back to this section.
        $form['actions']['submit']['#submit'][] = '_foia_annual_data_report_section_redirect';
      }

    }

    // Force a submit function to increase memory limit before core's submit.
    if ($form_id === 'node_annual_foia_report_data_edit_form') {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          array_unshift($form['actions'][$action]['#submit'], 'foia_annual_data_report_early_submit');
        }
      }
    }

  }

}

/**
 * For the Annual Data Report, redirect back to the section that was submitted.
 *
 * @param array $form
 *   Drupal form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Drupal form state.
 */
function _foia_annual_data_report_section_redirect(array &$form, FormStateInterface $form_state): void {
  // This section's part of the route was saved in the form.
  $route = 'entity.node.edit_form.' . $form['form_section']['#value'];
  // Redirect back to this page / section of the form.
  $form_state->setRedirect($route, ['node' => $form_state->getformObject()->getEntity()->id()]);
}

/**
 * Add ajax to a new annual report node to submit on agency field is set.
 *
 * @param array $form
 *   Form array passed from hook_form_form_id_alter().
 */
function foia_annual_data_report_ajax_new_node(array &$form) {

  // The 'change.agency' event corresponds to the event triggered in
  // the foia_change_report_agency library that is attached to this element.
  // This is a workaround for IE11, which does not fire the change event on
  // this input when selecting a value from the autocomplete dropdown list.
  $form['field_agency']['widget'][0]['target_id']['#ajax'] = [
    'callback' => 'foia_annual_data_report_create_node',
    'event' => 'change.agency',
    'progress' => [
      'type' => 'throbber',
      'message' => 'Please Wait...',
    ],
  ];

  $form['field_agency']['widget'][0]['target_id']['#attached']['library'][] = 'foia_annual_data_report/foia_change_report_agency';

}

/**
 * Add ajax to a existing annual report node to submit on agency field is set.
 *
 * @param array $form
 *   Form array passed from hook_form_form_id_alter().
 */
function foia_annual_data_report_ajax_existing_node(array &$form) {

  // The 'change.agency' event corresponds to the event triggered in
  // the foia_change_report_agency library that is attached to this element.
  // This is a workaround for IE11, which does not fire the change event on
  // this input when selecting a value from the autocomplete dropdown list.
  $form['field_agency']['widget'][0]['target_id']['#ajax'] = [
    'callback' => 'foia_annual_data_report_refresh',
    'event' => 'change.agency',
    'progress' => [
      'type' => 'throbber',
      'message' => 'Please Wait...',
    ],
  ];
  $form['field_agency']['widget'][0]['target_id']['#attached']['library'][] = 'foia_annual_data_report/foia_change_report_agency';

}

/**
 * Save the node and redirect back to the edit page for the node.
 *
 * @param array $form
 *   Form array passed from hook_form_form_id_alter().
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state passed from hook_form_form_id_alter().
 *
 * @return \Drupal\Core\Ajax\AjaxResponse
 *   AjaxResponse object to alert user and redirect them.
 */
function foia_annual_data_report_create_node(array $form, FormStateInterface
 $form_state) {

  $response = new AjaxResponse();

  $node = \Drupal::entityTypeManager()->getStorage('node')->create([
    'type' => 'annual_foia_report_data',
    'field_agency' => $form_state->getValue('field_agency'),
    'field_foia_annual_report_yr' => $form_state->getValue('field_foia_annual_report_yr'),
  ]);
  $node->save();

  $url = $node->toUrl('edit-form')->toString();

  $response->addCommand(new RedirectCommand($url));
  $response->addCommand(new AlertCommand("Please wait while the page refreshes"));

  return $response;
}

/**
 * Do all the magic to get the component list and update the Component options.
 *
 * @param array $form
 *   Form array passed from hook_form_form_id_alter().
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state passed from hook_form_form_id_alter().
 */
function foia_annual_data_report_refresh(array $form, FormStateInterface
 $form_state) {

  $node = \Drupal::routeMatch()->getParameter('node');
  $response = new AjaxResponse();
  $currentURL = Url::fromRoute('<current>');

  if ($node instanceof NodeInterface) {
    $nid = $node->id();
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);

    // @todo: If users change anything else it doesnt persist.
    $node->set('field_agency', $form_state->getValue('field_agency'));

    // Set as new revision.
    $node->setNewRevision(TRUE);
    $node->revision_log = 'Updated Agency for report';
    $node->setRevisionUserId(\Drupal::currentUser()->id());

    $node->save();

    $response->addCommand(new RedirectCommand($currentURL->toString()));
    $response->addCommand(new AlertCommand("Please wait while the page refreshes"));
  }

  return $response;
}

/**
 * Implements hook_form_submit().
 *
 * Set the memory limit to 1024M. Should only be used on Annual Report forms.
 */
function foia_annual_data_report_early_submit($form, FormStateInterface $form_state) {
  foia_annual_data_report_debug_log('Submitting Annual Report. Before setting memory');
  foia_annual_data_report_set_memory_limit();
  foia_annual_data_report_set_max_execution_time();
  foia_annual_data_report_debug_log('Submitting Annual Report. After setting memory');

}

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function foia_annual_data_report_node_load($entities) {
  // If there is an Annual Report being loaded and memory is not what we want
  // then set it.
  if (ini_get('memory_limit') !== foia_annual_data_report_get_config('annual_report_memory_limit')) {
    foreach ($entities as $entity) {
      if ($entity->bundle() === 'annual_foia_report_data') {

        foia_annual_data_report_debug_log('Loading Annual Report. Before setting memory');
        foia_annual_data_report_set_memory_limit();
        foia_annual_data_report_set_max_execution_time();
        foia_annual_data_report_debug_log('Loading Annual Report. After setting memory');

        // If we already set the memory limit, break out of the array.
        break;
      }
    }
  }
}

/**
 * Set the FOIA annual report year field's default value to the current year.
 *
 * This allows the auto_entitylabel module to rely on the
 * field_foia_annual_report_yr value when setting the title.
 *
 * @param array $form
 *   The annual_foia_report_data node add or edit form array.
 */
function foia_annual_data_report_set_default_report_year(array &$form) {
  $default_value = $form['field_foia_annual_report_yr']['widget'][0]['value']['#default_value'] ?? FALSE;
  if (!$default_value) {
    $form['field_foia_annual_report_yr']['widget'][0]['value']['#default_value'] = date('Y');
  }
}

/**
 * Set memory limit for override based on config.
 */
function foia_annual_data_report_set_memory_limit() {
  try {
    $config_value = foia_annual_data_report_get_config('annual_report_memory_limit');
  }
  catch (\InvalidArgumentException $e) {
    \Drupal::logger('foia_annual_data_report')->error('Invalid setting requested.');
  }

  if ($config_value) {
    ini_set('memory_limit', $config_value);
  }
}

/**
 * Set max execution time for override based on config.
 */
function foia_annual_data_report_set_max_execution_time() {
  try {
    $config_value = foia_annual_data_report_get_config('annual_report_max_execution_time');
  }
  catch (\InvalidArgumentException $e) {
    \Drupal::logger('foia_annual_data_report')->error('Invalid setting requested.');
  }

  if ($config_value) {
    ini_set('max_execution_time', $config_value);
  }
}

/**
 * Get the requested setting from this module's config.
 *
 * @param string $setting
 *   The name of the setting to be retrieved.
 *
 * @return string
 *   The value of the requested setting.
 */
function foia_annual_data_report_get_config(string $setting) {
  $allowed_settings = [
    'annual_report_max_execution_time',
    'annual_report_memory_limit',
    'debug_annual_report_memory_limit',
  ];
  if (!in_array($setting, $allowed_settings)) {
    throw new \InvalidArgumentException('Invalid setting.');
  }
  $value = \Drupal::config('foia_annual_data_report.settings')
    ->get($setting);

  return $value;
}

/**
 * Log debugging output if config value is set.
 *
 * @param string $message_base
 *   Base text to prepend to memory_limit when writing debugging message.
 */
function foia_annual_data_report_debug_log(string $message_base) {
  $debug = foia_annual_data_report_get_config('debug_annual_report_memory_limit');

  if ($debug) {

    $msg = $message_base . ': ' . ini_get('memory_limit');

    \Drupal::logger('foia_annual_data_report')->debug($msg);
  }
}


function foia_annual_data_report_menu_local_tasks_alter(&$data, $route_name) {
//  dump($route_name);
//  dump($data);
//  $data = [
//    '#type' => 'markup',
//    '#markup' => 'heynow',
//  ];
//  dump($data);
}
