<?php

/**
 * @file
 * FOIA Webform module.
 */

use Drupal\webform\WebformInterface;

/**
 * Programmatically add the foia_email handler to new webforms.
 */
function foia_webform_webform_insert(WebformInterface $webform) {
  $webform_handler_manager = \Drupal::service('plugin.manager.webform.handler');
  $webform_handler = $webform_handler_manager->createInstance('foia_submission_queue');

  // @todo: Add Submission Email if we add Agency Component entity reference.
  // Set default configuration.
  $webform_handler->setConfiguration([
    'id' => 'foia_submission_queue',
    'label' => 'FOIA Submission Queue',
    'handler_id' => 'foia_submission_queue',
    'status' => TRUE,
    'weight' => 0,
    'settings' => [
      'states' => ['completed'],
      'to_mail' => '',
      'to_options' => [],
      'cc_mail' => '',
      'cc_options' => [],
      'bcc_mail' => '',
      'bcc_options' => [],
      'from_mail' => 'default',
      'from_options' => [],
      'from_name' => 'default',
      'subject' => 'FOIA Request Submission',
      'body' => '[webform_submission:values:message:value]',
      'excluded_elements' => [],
      'html' => TRUE,
      'attachments' => FALSE,
      'debug' => 0,
      'reply_to' => '',
      'return_path' => '',
    ],
  ]);

  // Must update original id to prevent the below error.
  // Drupal\Core\Config\ConfigNameException: The machine name of the 'Webform'
  // bundle cannot be changed in
  // Drupal\Core\Config\Entity\ConfigEntityBundleBase->preSave()
  $webform->setOriginalId($webform->id());

  // Add handle to the webform, which triggers another save().
  $webform->addWebformHandler($webform_handler);
}
