<?php

/**
 * @file
 * FOIA Webform module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\WebformInterface;

/**
 * Programmatically add the foia_submission_queue handler to new webforms.
 */
function foia_webform_webform_insert(WebformInterface $webform) {
  $webform_handler_manager = \Drupal::service('plugin.manager.webform.handler');
  $webform_handler = $webform_handler_manager->createInstance('foia_submission_queue');

  $webform_handler->setConfiguration([
    'id' => 'foia_submission_queue',
    'label' => 'FOIA Submission Queue',
    'handler_id' => 'foia_submission_queue',
    'status' => TRUE,
    'weight' => 0,
    'settings' => [
      'states' => ['completed'],
      'to_mail' => '',
      'to_options' => [],
      'cc_mail' => '',
      'cc_options' => [],
      'bcc_mail' => '',
      'bcc_options' => [],
      'from_mail' => 'default',
      'from_options' => [],
      'from_name' => 'default',
      'subject' => 'FOIA Request Submission',
      'body' => '[webform_submission:values:message:value]',
      'excluded_elements' => [],
      'html' => TRUE,
      'attachments' => FALSE,
      'debug' => FALSE,
      'reply_to' => '',
      'return_path' => '',
    ],
  ]);

  // Must update original id to prevent the below error.
  // Drupal\Core\Config\ConfigNameException: The machine name of the 'Webform'
  // bundle cannot be changed in
  // Drupal\Core\Config\Entity\ConfigEntityBundleBase->preSave()
  $webform->setOriginalId($webform->id());

  // Add handle to the webform, which triggers another save().
  $webform->addWebformHandler($webform_handler);
}

/**
 * Implements hook_webform_submission_form_alter().
 */
function foia_webform_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $user = \Drupal::currentUser();
  if (!$form_state->isProgrammed() && !$user->hasPermission('use webforms in backstage')) {
    $form['#access'] = FALSE;
    $form['#markup'] = '<p>This form is only available via API.</p>';
  }
}
