<?php

/**
 * @file
 * FOIA Workflow module.
 */

use Drupal\core\Access\AccessResult;
use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountProxy;

/**
 * Implements hook_node_access().
 */
function foia_workflow_node_access(NodeInterface $node, $op, AccountProxy $account) {
  $type = $node->bundle();
  $workflow_state = $node->get('moderation_state')->getString();
  $author = $node->getOwner()->id();
  $user = $account->id();
  $is_report_type = (bool) ($type == 'annual_foia_report_data');
  $is_agency_admin = (bool) in_array('agency_administrator', $account->getRoles());
  $is_draft = (bool) (bool) ($workflow_state == 'draft');
  $is_not_author = (bool) ($author != $user);
  // Do not allow Agency Administrators to edit draft Annual Reports.
  if ($is_report_type && $is_agency_admin && $is_draft && $is_not_author && $op ==
    'update') {
    return AccessResult::forbidden();
  }
}
