<?php

/**
 * @file
 * FOIA UA module.
 */

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_toolbar_alter().
 */
function foia_ui_toolbar_alter(&$items) {
  $current_user = \Drupal::currentUser();

  $empty_item_cacheability = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  if ($current_user->hasPermission('access openapi api docs')) {
    $items['foia_api'] = [
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => t('API'),
        '#url' => Url::fromRoute('foia_ui.api'),
        '#options' => [
          'set_active_class' => TRUE,
        ],
        '#attributes' => [
          'class' => ['toolbar-icon', 'toolbar-icon-system-modules-list'],
        ],
      ],
      '#weight' => -30,
    ];
  }
  else {
    $items['reservoir_api'] = $empty_item_cacheability;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function foia_ui_form_node_annual_foia_report_data_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['actions']['validate_button'] = [
    '#type' => 'button',
    '#value' => t('Validate'),
    '#attached' => [
      'library' => [
        'foia_ui/jquery_validation',
        'foia_ui/foia_ui_validation',
      ],
      'drupalSettings' => [
        'foiaUI' => [
          'foiaUISettings' => [
            'formID' => '#node-annual-foia-report-data-edit-form',
          ],
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function foia_ui_form_node_annual_foia_report_data_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['actions']['validate_button'] = [
    '#type' => 'button',
    '#value' => t('Validate'),
    '#attached' => [
      'library' => [
        'foia_ui/jquery_validation',
        'foia_ui/foia_ui_validation',
      ],
      'drupalSettings' => [
        'foiaUI' => [
          'foiaUISettings' => [
            'formID' => '#node-annual-foia-report-data-form',
          ],
        ],
      ],
    ],
  ];
}
