<?php

/**
 * @file
 * PHPDocX Drupal 8 Plugin.
 *
 * This plugin allows to easily export Drupal nodes to DOCX, converting the HTML
 * of the nodes content, as well as working as a base to generate other plugins.
 */

/**
 * Implements hook_theme_suggestions_alter().
 */
function node_to_docx_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'node_to_docx' && $variables['elements']['#view_mode'] == 'node_to_docx') {
    $node = $variables['elements']['#node'];
    $suggestions = [];
    $suggestions[] = 'node__node_to_docx';
    $suggestions[] = 'node__' . $node->getType() . '__node_to_docx';
    $suggestions[] = 'node__' . $node->id() . '__node_to_docx';
  }
}

/**
 * Implements hook_help().
 */
function node_to_docx_help($route_name) {
  $output = NULL;
  // Render template when page is node to docx help page.
  if ($route_name == 'help.page.node_to_docx') {
    $help_template = [
      '#theme' => 'node_to_docx_help_admin',
    ];
    $output = drupal_render($help_template);
  }
  return $output;
}

/**
 * Implements hook_theme().
 */
function node_to_docx_theme($existing, $type, $theme, $path) {
  return [
    'node_to_docx_help_admin' => [
      'template' => 'help-admin',
    ],
    'node_to_docx' => [
      'template' => 'node--node-to-docx',
      'render element' => 'elements',
      'file' => 'node_to_docx.theme.inc',
    ],
  ];
}
