<?php

/**
 * @file
 * FOIA Webform Template Module.
 */

use Drupal\webform\WebformInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_insert().
 */
function webform_template_webform_insert(WebformInterface $webform) {
  $templateController = \Drupal::service('webform_template.template_controller');
  $templateController->addDefaultFields($webform);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function webform_template_form_webform_form_alter(array &$form, FormStateInterface $form_state) {
  // Remove edit/delete links from fields provided by the template.
  $templateController = \Drupal::service('webform_template.template_controller');
  $templateController->preprocessWebformForm($form, $form_state);
}

/**
 * Implements hook_webform_element_configuration_form_alter().
 */
function webform_template_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  $element['#element_validate'][] = 'webform_template_element_validate';
  $pattern = '/\/admin\/structure\/webform\/manage\//i';
  $current_path = \Drupal::service('path.current')->getPath();
  $url = preg_replace($pattern, '', $current_path);
  $url_ary = explode('/', $url);
  // Save webform ID for use in validation function.
  $element['#attributes']['webform_id'] = $url_ary[0];
}

/**
 * Webform element custom validation.
 *
 * @param array $element
 *   The element being processed.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param array $form
 *   An associative array containing the structure of the form.
 */
function webform_template_element_validate(array &$element, FormStateInterface $form_state, array &$form) {
  $values = $form_state->getValues();
  // Get form field key.
  $values = ($values['key'] !== NULL) ? $values['key'] : $values;
  $templateController = drupal_static(__FUNCTION__);
  if (!isset($templateController)) {
    $templateController = \Drupal::service('webform_template.template_controller');
  }
  $use_foia_template = $templateController::TEMPLATESTATUSDEFAULT;
  if (isset($element['#attributes']['webform_id'])) {
    $use_foia_template = $templateController->getTemplateConfiguration($element['#attributes']['webform_id']);
  }

  // Validate if foia template in use.
  if (isset($use_foia_template) && ($use_foia_template == '1')) {
    $templateElements = array_keys($templateController->templateElements);
    if (!in_array($values, $templateElements)) {
      $form_state->setErrorByName($values, t('Error field: "@field", Please contact the site administrator.', ["@field" => $values]));
    }
  }
}
