<?php

/**
 * @file
 * Contains foia_request.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function foia_request_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the foia_request module.
    case 'help.page.foia_request':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('High-level information store to maintain an audit trail of FOIA Requests.') . '</p>';
      return $output;

    default:
  }
}
