<?php
/**
 * @file
 * Module code for FOIA Agency Component.
 */

use \Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function foia_agency_component_entity_bundle_field_info_alter(array &$fields, EntityTypeInterface $entity_type, $bundle) {

  if ($entity_type->id() === 'node' && $bundle === 'agency_component') {
    $fields['field_agency_comp_abbreviation']->addConstraint('AgencyComponentUniqueAbbreviation', []);
  }
}
