name: Deploy to staging
on:
  push:
    branches:
      - release*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Acquia known hosts
        run: |
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - name: Install dev dependencies
        run: |
          composer install
      - name: Build the artifact
        run: |
          vendor/bin/blt deploy --branch="staging-build" --commit-msg="Automated deployment of a release branch" --verbose --ignore-dirty
