name: Deploy to dev
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACLI_KEY: ${{ secrets.ACLI_KEY }}
      ACLI_SECRET: ${{ secrets.ACLI_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Acquia known hosts
        run: |
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - name: Install dev dependencies
        run: |
          composer install

      - name: Install Acquia CLI
        run: |
          curl -OL https://github.com/acquia/cli/releases/latest/download/acli.phar
          chmod +x acli.phar
          sudo mv acli.phar /usr/local/bin/acli

      - name: Push artifact to Acquia
        run: |
          git config --global user.email "no-reply@usdoj.gov"
          git config --global user.name "Automated Deployment"
          export AH_ORGANIZATION_UUID=8401c2a7-d5ef-11e3-9eb3-22000b04072f
          acli login --key=${{ secrets.ACLI_KEY }} --secret=${{ secrets.ACLI_SECRET }} -vvv
          acli push:artifact --destination-git-branch=develop-build -vvv

