name: Test PRs

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Set up ddev
        uses: jonaseberle/github-action-setup-ddev@v1
      - name: Initialize ddev
        run: ddev start
      - name: Set up the site
        run: |
          ddev composer install
          ddev exec blt setup || true
          ddev drush cim
          ddev drush cr
      - name: Run tests
        run: |
          ddev composer show drupal/lightning_core
          ddev exec blt tests:behat:init
          ddev exec blt tests:behat
