name: Test PRs

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Set up ddev
        uses: jonaseberle/github-action-setup-ddev@v1
      - name: Set up the site
        run: |
          ddev composer install
          ddev exec blt setup || true
          ddev drush cim
          ddev drush cr
      - name: Validate code
        run: blt validate
      - name: Run tests
        run: ddev exec vendor/bin/behat --config=tests/behat/behat.yml --stop-on-failure --strict
      - name: Upload screenshots of failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tests/behat/screenshots/*.png
